library(astsa)
data(jj)
jj
ts=ts(rnorm(48), start=c(2293,6), frequency=12)
plot(jj,ylab="Earnings per Share")
plot(ts)
k = c(.5,1,1,1,.5)
k = k/sum(k)
fjj=filter(ts,k,method=c("convolution"),sides=2)
plot(jj)
lines(fjj,col="red")
lines(lowess(jj), col="blue", lty="dashed")
